#!/usr/bin/env python3
# -*- coding: utf-8 -*-
from sys import argv
import tkinter as tk
print(argv[0]) # Print current file
print(argv[1]) # Print resources folder
app = tk.Tk()
tk.Label(text = 'Hello, World!').pack()
app.mainloop()